### ISSUE TITLE
OTU from q2 taxa collapse

### ISSUE THREAD

**Issue by ARW-UBT** [mestaki/qiime2-to-BugBase#2]
Hi @mestaki 
I followed your q2-to-BugBase tutorial, and it worked just fine with my own data and GG references v. 13.8. 
I am wondering whether some other q2 artifacts like collapsed taxonomic tables (q2 taxa collapse) would allow to create biom files compatible with BugBase. The data within these artifact are similar to the feature-table-tax-biom1.biom at the end of your turorial, with some differences. 1) The feature identifier is replaced with the taxonomy, and 2) the taxonomy is not the last column in this table. And I hope that the absence of empty spaces in the taxonomy will be tolerated. 

The idea behind my question is whether there is a possibility to use taxonomic classification from 'qiime feature-classifier classify-sklearn' obtained with the most recent GG release (2022.10.backbone.v4.nb.qza available on Qiime2 Docs) together with feature tables as input to BugBase. 
But I got stuck how to add taxonomic classification to feature tables other than q2 taxa collapse...
In particular: 'q2 vsearch cluster-features-closed-reference' creates a feature table replacing the DADA2 feature id with the GG feature id (although I was assuming that the "Feature identifiers will be inherited from the centroid feature of each cluster" as stated by the --help output). And this is different in 'q2 feature-classifier' which keeps the DADA2 feature IDs.  

My idea was to combine outputs from q2-dada2 (table.qza) with q2-feature-classifier (classifier.qza; I consider this as a bridg table from dada2 ID to taxonomy, right?) and I would appreciaty any ideas how to get this done. 

Best regards
:-)

**Comment by mestaki** [comment]
Hi @ARW-UBT,

Thanks for your interest here. So there's a few different issues with your proposed approach, the most important one being that BugBase will not be able to use Greengenes2 taxonomy the way you want it. BugBase needs the input to be exactly in original greengenes taxonomy format (including separator characters) for it to run PICRUSt under the hood and then classify phenotypes. GG2 is a significant update and change to the original GG, which is why it is not just a release update, but a whole new tool. This means the taxonomy is significantly different and mainly has adopted the GTDB nomenclature.
That being said, it is possible you could find a way to use a GG2 table into BugBase, however, BugBase would just drop all the taxon that are not in its reference database, which is greengenes 1. Meaning even if we found a workaround, fixed the formatting, it would not actually yield any results, in fact you will likely lose many taxa if the nomenclature has changed in GG2, which as I mentioned, it has.

To be honest, BugBase could use a lot of improvements but I don't see that happening anytime soon, I haven't seen any updates on their repo in years and their pre-print has still not been published yet after many years. If you or anyone is going to invest a bit of time to improve its usage, my suggestions are a) enable the use of ASVs the same way PICRUSt2 did by utilizing phylogeny, or b) rebuild all its reference data (ex 16S copy number, phenotype tables, functional tables etc) with Greengenes2. Ideally, both! But I dream...

**Comment by ARW-UBT** [comment]
Hi @mestaki 
Thank you for your very informative comments to my questions. I can see the issues now much clearer. Let's see, sometimes dreams come true...
Best regards,
